### ISSUE TITLE
Implement CRUD Queries

### ISSUE THREAD

**Issue by AsalaKM** [FACG5/Qattan-foundation#2]
Those are all of the queries according to the flow of the pages:

**User**
 - [x] getUserData

**Ticket**
- [x] getLatestTicket
- [x] getTicketByName
- [x] getTicketDetails
- [x] getTicketCount
- [x] getSolvedCount
- [x] getNotSolvedCount
- [x] getSupports
- [x] getLoans
- [x] getTicketByStatus
- [x] getTicketByPeriod
- [x] addTicket
- [x] updateTicket

**Inventory**
- [x] getInventory
- [x] AddInventory
- [x] updateInventory
- [x] getInventoryByName

**Comment by FarahZaqout** [comment]
You may close this issue now.
